# use latest ubuntu as the infrastructure environment
dist: bionic

# specify language used
language: go

env: GO111MODULE=on

go: "1.14"

# specify use of docker
services:
  - docker

# golang linter install
before_install:
  - go get -v golang.org/x/lint/golint

jobs:
  include:
    - stage: Testing - Linting / Unit Tests
      script:
        - golint goapi

    - stage: Build
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t $REPO:${TRAVIS_COMMIT} --build-arg vers=$(jq '.version' metadata.json) --build-arg desc="$(jq '.description' metadata.json)" --build-arg sha=${TRAVIS_COMMIT} -f build.Dockerfile .
        - docker image ls
        - docker tag $REPO:${TRAVIS_COMMIT} $DOCKER_USERNAME/$REPO:$(jq -r '.version' metadata.json)
        # - docker tag $REPO:${TRAVIS_COMMIT} $DOCKER_USERNAME/$REPO:${TRAVIS_COMMIT}
        - docker push $DOCKER_USERNAME/$REPO:${TRAVIS_COMMIT}

    - stage: Run
      script:
        - docker run --rm -d -p 8080:8080 $DOCKER_USERNAME/$REPO:${TRAVIS_COMMIT}
        - sleep 15
        - curl http://localhost:8080/
        - curl http://localhost:8080/version
